### ISSUE TITLE
 classes cannot be resolved

### ISSUE THREAD

**Issue by just4phil** [StrongJoshua/libgdx-inGameConsole#1]
hi
thx for sharing!!
i forked the repo and cloned it to my pc. then i imported the project to my game workspace via gradle and added it to the build path and to order/export.
but when i try to import the classes they cannot be resolved.
(i guess a stupid error on my side)
...
any suggestions?

bye
phil

**Comment by StrongJoshua** [comment]
The way I added it to my projects was that I converted the console project to a Maven project (`Configure -> Convert to Maven`), the project POM details don't matter, and the same with the project I'm addit the console to, then I just added the console project as a dependency (`Maven -> Add Dependency`). This worked for me, but I'll have a look at adding it to the build path (I didn't realize it made the project build differently) after school.

**Comment by StrongJoshua** [comment]
Please review the main README and make sure your clone is up-to-date!
