### ISSUE TITLE
Issue with invocation with overloaded methods.

### ISSUE THREAD

**Issue by piotr-j** [StrongJoshua/libgdx-inGameConsole#10]
While working on a lib to get it to work with GWT, Ive found a bug in `execCommand(String command)`. Overloading methods doesnt work, since the methods returns on first failure. This can be easily fixed by removing `return` at line 487. However, the log message and stacktrace remains and makes it ugly. Checking primitive types is little annoying, so I propose that exceptions are logged after the loop, if all possible candidates failed. 

Ill PR working GWT implementation once this issue is resolved.

**Comment by StrongJoshua** [comment]
Getting this to work with GWT has been difficult, I agree. I also cannot test to see if what I have done works because the game using this library won't run, but it did compile. I'll sync my local changes with the master branch and maybe you can check if I did it correctly.

**Comment by piotr-j** [comment]
Getting it to work wasnt so bad, replaced reflection with libgdx stuff and it works. However, the `Date` stuff is a lot harder. I dont need it for the project im working on, but i just removed relevant code. No idea how to solve it cleanly.

**Comment by piotr-j** [comment]
Ive added a repo with the test gwt thing im working on, its very simple and you should be able to run it.
Edited console src is included.
Things i did to get it to work:
- replaced java reflection with libgdx wrappers
- removed Date stuff from `LogEntry`
- added Console.gwt.xml
- added stuff to GdxDefinitions in html
https://github.com/piotr-j/gwt-testing

**Comment by StrongJoshua** [comment]
Oh ok, so you actually included the console code in the game code. My implementation should still work with Maven. Check out this post on the libgdx forums: http://www.badlogicgames.com/forum/viewtopic.php?f=11&t=18831 that error may or may not come from my console's code. I'll have to look into it further.

**Comment by piotr-j** [comment]
I only did that because i didnt bother to compile it and add as jar for quick test project. Here it is on my site, f2 to show console.
http://www.piotrjastrzebski.io/static/gwttest/index.html

**Comment by StrongJoshua** [comment]
Have you tried the commands such as printLog()? I ask because I wonder where it would print to and if I should see if I could add a feature to disable this command if it detects it is being run from HTML (since anyone could have it print and possibly clog up your entire server).

**Comment by StrongJoshua** [comment]
Btw, have you been able to get the console to work in HTML without passing it your own skin? It seems to be unable to read its default skin file...

**Comment by piotr-j** [comment]
It didnt want to work on desktop when i just copied source, so i didnt try on gwt. But it wouldnt be surprising if it didnt work on gwt as it uses classpath. GWT is a second class citizen where backends are concerned. I think the best option is to provide GWT compatible implementation, like box2d. Im not certain of the details how that works.

**Comment by piotr-j** [comment]
Since you solved these problems, it should be ok to close this.

**Comment by StrongJoshua** [comment]
I hope I solved them :3
