### ISSUE TITLE
Add method "Console.setHidden(boolean value)"

### ISSUE THREAD

**Issue by bladecoder** [StrongJoshua/libgdx-inGameConsole#21]
I would like to show/hide the console from a button or programatically when certain errors happen. It would be useful to have the method `Console.setHidden(boolean value)` to allow this.

**Comment by StrongJoshua** [comment]
Hiding it using a button is already an option. Just use the setKeyID() function. This key will hide and show the console. I'll give you that the name isn't very descriptive and I agree that a basic setHidden() function would be useful. I'll add that soon.

**Comment by StrongJoshua** [comment]
Updated in 770fd7947adc968c9942138a28ef1e33d618b9d9
Should be deploying this to Maven within 24 hours

**Comment by Namek** [comment]
Guys, dont name it like that. Go with setVisible().

19.09.2016 05:51 "Jan Risse" <notifications@github.com> napisał(a):

**Comment by bladecoder** [comment]
@StrongJoshua with a button I meant that I would like to show/hide with an UI button, not a keyboard key.

@Namek `Console.setVisible(boolean value)` to show/hide the console will be perfect.

**Comment by StrongJoshua** [comment]
@Namek Haha I don't know why I didn't think about that. I didn't actually have time to deploy yesterday so that is still easily changed. I'll get on that.

**Comment by StrongJoshua** [comment]
Added in version **0.5.2**
