### ISSUE TITLE
Print Stack Trace

### ISSUE THREAD

**Issue by nibuen** [StrongJoshua/libgdx-inGameConsole#22]
Would be nice to print the stack trace instead of just the message like so:

      catch (ReflectionException e) {
                    String msg = e.getMessage();
                    if (msg == null || msg.length() <= 0 || msg.equals("")) {
                        msg = "Unknown Error";
                        e.printStackTrace();
                    }
                   
                   if(showConsoleStackTrace) {                   
                      StringWriter sw = new StringWriter();
                      PrintWriter pw = new PrintWriter(sw);
                      e.getCause().getCause().printStackTrace(pw);
                         log(sw.toString(), LogLevel.ERROR);
                   }  else {
                      log(msg, LogLevel.ERROR);
                   }
                    return;
                }

**Comment by BenMcLean** [comment]
This feature would probably have to be marked as GWT incompatible unless it's written very cleverly to use the libGDX emulation of reflection for GWT.

**Comment by nibuen** [comment]
@BenMcLean This code is already there as this in AbstractConsole:  


catch (ReflectionException e) {
					String msg = e.getMessage();
					if (msg == null || msg.length() <= 0 || msg.equals("")) {
						msg = "Unknown Error";
						e.printStackTrace();
					}
					log(msg, LogLevel.ERROR);
					return;
				}

**Comment by StrongJoshua** [comment]
I have implemented this, it should be live soon.

**Comment by StrongJoshua** [comment]
Released in 0.5.3
