### ISSUE TITLE
Possibility to set a font

### ISSUE THREAD

**Issue by jiff88** [StrongJoshua/libgdx-inGameConsole#26]
I think in most apps console font would be somehow special / different than a "default-font". Please, can you implement a way how can we say smth. like "console-font", which would be present in my skin of course? That would be awesome. Without this, console forces me to put a font suitable for it as a default one, which is not suitable for the rest of the app. Thank you!

**Comment by StrongJoshua** [comment]
Sorry this is incredibly late, but added in 82c3b0f240554d64a684ba8e450c9232ee536657

**Comment by jiff88** [comment]
Thank you very much..

**Comment by StrongJoshua** [comment]
I released version 0.6.0, which contains this change. Let me know if there are any issues.
