### ISSUE TITLE
Commit eclipse formatter

### ISSUE THREAD

**Issue by Dimitri0xff** [StrongJoshua/libgdx-inGameConsole#29]
I've tried using the [latest libGDX formatter](https://github.com/libgdx/libgdx/blob/master/eclipse-formatter.xml) but I get slightly different results if I do formatting on a file.
So please commit the exact version you are using.

**Comment by StrongJoshua** [comment]
Just reformatted everything (using the libGDX formatter). Let me know if I missed anything.
