### ISSUE TITLE
Signing stuff on Gradle causes problems

### ISSUE THREAD

**Issue by BenMcLean** [StrongJoshua/libgdx-inGameConsole#32]
I get jars of libgdx-inGameConsole made through Jitpack. As [this build log](https://jitpack.io/com/github/StrongJoshua/libgdx-inGameConsole/9b4d3382bc/build.log) shows, the signing stuff in build.gradle causes the build to fail, presumably for anyone using gradle except StrongJoshua himself.

I've been able to work around this over on [my fork](https://github.com/BenMcLean/libgdx-inGameConsole/commits/master) by simply stripping out all signing related stuff from build.gradle. But what you'll probably want to do to address this is to configure gradle properly so that it only attempts this signing stuff on request.

**Comment by playmyskay** [comment]
maybe you simply have to add a file named "gradle.properties" with the following content:
```
ossrhUsername=
ossrhPassword= 
```

Hope this helps.

**Comment by StrongJoshua** [comment]
@playmyskay Is right. You need to specify a signing identity. It should let you sign because nothing in the signing portion of the build.gradle is specific to any key.
