### ISSUE TITLE
Console Looks Weird on Resize

### ISSUE THREAD

**Issue by Ktar5** [StrongJoshua/libgdx-inGameConsole#45]
https://i.imgur.com/WdciDZn.png Normal windowed mode
However when I go to maximize my window: https://i.imgur.com/DEm0TnU.png 

Not sure what's goin on.

**Comment by Blunderchips** [comment]
There is no way to resize the stage that the console sits on

**Comment by StrongJoshua** [comment]
No follow-up. Closing this issue.

**Comment by tlitookilakin** [comment]
Having the same problem in v1.0.0 https://imgur.com/a/FFqRbwx
This seems to occur no matter what viewport type is applied to the main stage.
